name: Frontend CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Typecheck
        run: npx tsc --noEmit || echo "No TS config, skipping typecheck."
      - name: Build
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: frontend/.next
      - name: Vercel Preview URL
        if: always()
        run: |
          echo "Preview: https://vercel.com/your-org/your-project/deployments"
